//! Predefined model registry, auto-generated from `models/local.toml`
//! at build time.
//!
//! Use [`resolve`] to map an alias or full repo id to the canonical
//! HF repo path. Use [`list`] to get all available models for UI
//! display.

/// Which mlx-swift-lm factory a model belongs to. `Llm` models accept
/// text only; `Vlm` models accept text plus image (and sometimes video)
/// content parts.
///
/// Declared *before* the `include!` so the generated `MODEL_REGISTRY`
/// can reference `ModelKind::Llm` / `ModelKind::Vlm` variants directly
/// — no stringly-typed runtime parse, no panic branch, the enum
/// invariant is enforced by rustc at build time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModelKind {
    Llm,
    Vlm,
}

/// A model entry from the registry.
#[derive(Debug, Clone, Copy)]
pub struct ModelEntry {
    /// Lowercase alias: `"family-param_size-quant"` (e.g. `"qwen3.5-2b-4bit"`).
    pub alias: &'static str,
    /// Full HuggingFace repo id (e.g. `"mlx-community/Qwen3.5-2B-MLX-4bit"`).
    pub repo_id: &'static str,
    /// Whether the model is an LLM or a VLM.
    pub kind: ModelKind,
    /// Approximate disk size in megabytes (0 = unknown).
    pub size_mb: u64,
    /// Model family (e.g. `"qwen3.5"`, `"llama4-scout"`).
    pub family: &'static str,
    /// Parameter size (e.g. `"0.8b"`, `"17b-16e"`, `"360m"`).
    pub param_size: &'static str,
    /// Quantization level (e.g. `"4bit"`, `"8bit"`).
    pub quant: &'static str,
    /// Architecture / model_type from HuggingFace config (e.g. `"qwen2"`, `"llama"`).
    pub arch: &'static str,
}

// Generated by build.rs from models/local.toml.
include!(concat!(env!("OUT_DIR"), "/model_registry.rs"));

/// List all predefined models.
pub fn list() -> &'static [ModelEntry] {
    MODEL_REGISTRY
}

/// Resolve a model name to a HuggingFace repo id.
///
/// Accepts:
///   * A full repo id (`"mlx-community/Qwen3.5-2B-MLX-4bit"`) — returned as-is.
///   * A lowercase alias (`"qwen3.5-2b-4bit"`) — looked up in the registry.
///
/// Returns `None` if the input is not a full repo id (no `/`) and
/// not a known alias.
pub fn resolve(model: &str) -> Option<&'static str> {
    // Full repo id
    if model.contains('/') {
        return Some(
            MODEL_REGISTRY
                .iter()
                .find(|e| e.repo_id == model)
                .map(|e| e.repo_id)
                .unwrap_or_else(|| {
                    // Not in registry but looks like a repo id — pass through.
                    // Leak is fine: this is called once per model load.
                    Box::leak(model.to_string().into_boxed_str())
                }),
        );
    }

    // Alias lookup (case-insensitive)
    let lower = model.to_lowercase();
    MODEL_REGISTRY
        .iter()
        .find(|e| e.alias == lower)
        .map(|e| e.repo_id)
}
